name: Build ThornedLibrary

on:
  push:
    branches:
      - main
      - library 
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat

      - name: Install SFML
        run: |
          .\vcpkg\vcpkg install sfml:x64-windows

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DDEV_MODE=ON -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DSFML_DIR=${{ github.workspace }}/vcpkg/installed/x64-windows/share/SFML

      - name: Build the project
        run: |
          cd build
          cmake --build . --config Debug

      - name: Copy header files
        run: |
          mkdir -p "${{ github.workspace }}/bin/Debug/include/GUI"
          mkdir -p "${{ github.workspace }}/bin/Debug/include/XML"
          Copy-Item -Path "${{ github.workspace }}/GUI/*.hpp" -Destination "${{ github.workspace }}/bin/Debug/include/GUI/" -Recurse -Force
          Copy-Item -Path "${{ github.workspace }}/GUI/components/*.hpp" -Destination "${{ github.workspace }}/bin/Debug/include/GUI/components/" -Recurse -Force
          Copy-Item -Path "${{ github.workspace }}/GUI/form/*.hpp" -Destination "${{ github.workspace }}/bin/Debug/include/GUI/form/" -Recurse -Force
          Copy-Item -Path "${{ github.workspace }}/XML/*.hpp" -Destination "${{ github.workspace }}/bin/Debug/include/XML/" -Recurse -Force
          Copy-Item -Path "${{ github.workspace }}/XML/*.h" -Destination "${{ github.workspace }}/bin/Debug/include/XML/" -Recurse -Force
