name: Build ThornedLibrary

on:
  push:
    branches:
      - main
      - library 
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat

      - name: Install SFML
        run: |
          .\vcpkg\vcpkg install sfml:x64-windows

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DDEV_MODE=ON -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DSFML_DIR=${{ github.workspace }}/vcpkg/installed/x64-windows/share/SFML

      - name: Build the project
        run: |
          cd build
          cmake --build . --config Debug

      - name: Debug directory structure
        run: |
          Write-Host "Current directory structure:"
          Get-ChildItem -Path "${{ github.workspace }}" -Recurse
